server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: Temporal_Behavior_Analytics
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres??currentSchema=test
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
        reWriteBatchedStatements: true
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 30

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      order_inserts: true
      order_updates: true
      jdbc:
        batch_size: 100
    open-in-view: false
  web:
    resources:
      add-mappings: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%X{request_id:----}]%m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"



springdoc:
  swagger-ui:
    path: /swagger-push-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**